import React, { Component } from 'react';
import { Grid, Row } from 'react-bootstrap';
import dogs from './dogs.json';
import Thumbnails from './Thumbnails';

/*
Gallery file for the gallery that gets the dogs.json file to populate the grid and modal.
Also call the thumbnails component.  Grid and modal UI generated by react bootstrap.
*/

const data = dogs;

export class Gallery extends Component {
  render() {
      return (
		<Grid>
			<Row class="row-eq-height">
				{data.dogs.map(function(images, index){
					return (<Thumbnails gallery={images.image} />);
				})}
			</Row>
		</Grid>
    );
  }
}